### ISSUE TITLE
Feature: Allow to specify more than one type of comments

### ISSUE THREAD

**Issue by SanmayJoshi** [penibelst/jekyll-compress-html#100]
## Summary
Currently, user can specify one type of comment, so that commented content is removed in output. Many times users have CSS or JS code in html file, and such CSS or JS code also has comments, removing which would save some memory space.

## Current behavior
Only one type of comment can be specified in _config.yml file.

## Proposed behavior
More than one type of comments can be specified in _config.yml file.

## Possible solution
Allow users to specify multiple arrays of `size = 2` each.
For example:
In _config.yml
```
compress_html:
  comments:
    - ["<!-- ", " -->"]
    - ["/* ", " */"]
```

## Notes
May take a toll on execution time if user specifies more types of comments. But, it would be up to user whether to specify multiple types of comments or not, thus user would have a choice in trade-off.

**Comment by jnvsor** [comment]
I'm going to rant for a bit because this is the umpteenth time (#95 #88 #85 #82 #80 ...) I've seen this feature request, and I want somewhere to point the next umpteen. (So don't take it personally)

There are way too many edge cases to make this remotely worth it.

* A JS comment shouldn't count outside of script tags
* Does a JS comment end when a script tag ends?
* Should an HTML comment count inside of script tags?
* What about HTML comments inside script tag attributes?
* What about HTML comments inside JS strings?
* What about JS comments inside JS strings?
* What about script tags inside JS strings?
* What about JS comments inside quotes inside JS strings?
* What about JS comments inside quotes inside JS strings inside script tags that happen to be inside `<pre>` where we disable compression entirely to preserve whitespace?!
* What about CSS comments??!?

Now add that because it's implemented by splitting, you can't nest anything. Nest any 2 of the above and the code won't work.

The fastest way to implement this would be to make a fully fledged dom parser. In liquid.

Do you want a render time measured in bytes per hour? Because that is how you get a render time measured in bytes per hour.

Just minify your JS and keep it in a separate file

**Comment by SanmayJoshi** [comment]
Oh...no worries. I had searched in issues but couldn't find any with current title as my phrase(this issue is literally umpteenth, sry for that); I hope this issue will help other users.

I see you have plenty of points. I hadn't given it thought to the extent you have. Anyway, it is nice to know that its absence is intentional. :)

**Comment by doktorbro** [comment]
i agree with @jnvsor: «Just keep your JS in a separate file».
