### ISSUE TITLE
Disable/enable

### ISSUE THREAD

**Issue by MattGreyDesign** [penibelst/jekyll-compress-html#77]
Really useful tool! As an enhancement, it would be nice to have the option to disable or enable when required whilst developing. I found I sometimes needed to disable the layout compression for various reasons so I made a simple configurable condition.

```
compress_html:
  enabled: true
```
```
{% if site.compress_html.enabled %}
  Compression magic
{% else %}
  {{ content }}
{% endif %}
```

**Comment by xHN35RQ** [comment]
This is already available via [ignore.envs](http://jch.penibelst.de/#ignoreenvs). Set a Jekyll environment variable and compression will automatically toggle on and off for your based on whether you're in development or production.

**Comment by xHN35RQ** [comment]
This is already available via [ignore.envs](http://jch.penibelst.de/#ignoreenvs). Set a [Jekyll environment variable](http://jekyllrb.com/docs/configuration/#specifying-a-jekyll-environment-at-build-time) and compression will automatically toggle on and off for your based on whether you're in development or production.

**Comment by jnvsor** [comment]
@xHN35RQ spot on

**Comment by MattGreyDesign** [comment]
My bad, hadnt realised this. However, couldn't get that to work, where would I set the environment variable, in the `config.yml`?

**Comment by xHN35RQ** [comment]
It's set on the command line as you run `jekyll build` - from the docs:

> By specifying the option in the build command, you avoid having to change values in your configuration files when moving from one environment to another.

The link I provided goes into further detail: http://jekyllrb.com/docs/configuration/#specifying-a-jekyll-environment-at-build-time

**Comment by AdityaAnand1** [comment]
Hey there, I've tried:

`bundle exec jekyll serve --incremental JEKYLL_ENV=development`

  It doesn't really seem to have an effect. I use `bundle exec` because, as explained by some stackoverlfow answer, jekyll and some of the plugins have hiccups when used on windows. Could `bundle exec` be a problem?

Also, What exactly am I supposed to have in:
`  ignore:
    `envs`: []`

the envs array? Ideally, I'd like it to assume development environment unless I specify it's production. I've tried the following, to no avail:
`envs: [local, development, production, JEKYLL_ENV]`

@xHN35RQ the [docs](http://jekyllrb.com/docs/configuration/#specifying-a-jekyll-environment-at-build-time) seem to suggest that this is the case (development is default). So, technically compression shouldn't run at all unless we explicitly specify a production build, but nothing I do seems to disable the compression. 

[This](http://www.petethompson.net/blog/web/2015/02/28/environments-in-jekyll/) article suggested adding
`environment: development`

to _config.yml, but again it had no effect.

What am I missing?

**Comment by jnvsor** [comment]
Environment variables have to be specified before the command or exported:

```bash
JEKYLL_ENV=development bundle exec jekyll serve --incremental
```

```bash
export JEKYLL_ENV=development
bundle exec jekyll serve --incremental
```

Though this is basic shell stuff and not really JCH specific. Are you sure you're setting the right vars?

```yaml
compress_html:
  ignore:
    envs: [development]
```

**Comment by AdityaAnand1** [comment]
Ahhh! That's it. I'm on windows so I had to use

`set JEKYLL_ENV=development`

It's working now, thanks @jnvsor !
