### ISSUE TITLE
Jekyll v3.5 supports Liquid whitespace control

### ISSUE THREAD

**Issue by jmlntw** [penibelst/jekyll-compress-html#93]
Jekyll v3.5+ supports [Liquid template whitespace control](https://help.shopify.com/themes/liquid/basics/whitespace) (`{%-`, `-%}`, `{{-`, `-}}` tags). Maybe there is no need to write `compress.html` in a single line.

**Comment by jnvsor** [comment]
I've decided not to use these for a few reasons:

* Using those tags would mean dropping support for all older versions of Jekyll
* It's unlikely anyone will want to tweak the source code of JCH since it's such an arcane eldritch horror given liquid form
  * If someone's capable of doing that, they won't be complaining about running the compiler

Thanks for the suggestion though
